<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="https://raw.githubusercontent.com/styd/impression/main/images/fork-me.png"
     usemap="#fork-me">
<map name="fork-me">
  <area shape="poly"
        alt="Fork me on GitHub"
        title="Fork me on GitHub"
        coords="0,0,60,0,180,120,180,180"
        href="https://github.com/styd/impression">
</map>

<style>
  img {
    position: fixed;
    top: 0;
    right: 0;
    width: 120px;
  }

  @media screen and (min-width: 768px) {
    img {
      width: unset;
    }
  }
</style>
